/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.TelefonoDAO;
import ec.edu.ups.dao.UsuarioDAO;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author braya
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private VentanaIniciarSesion ventanaIniciar;
    private VentanaRegistrarUsuario ventanaRegistrar;
    private UsuarioDAO usuarioDAO;
    private TelefonoDAO telefonoDAO;
    private ControladorUsuario ctrlUsuario;
    private ControladorTelefono ctrlTelefono;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        menuItemCerrar.setVisible(false);
        menuAgenda.setVisible(false);
        //instanciar DAO's
        usuarioDAO = new UsuarioDAO();
        telefonoDAO = new TelefonoDAO();
        //instanciar Controladore
        ctrlUsuario = new ControladorUsuario(usuarioDAO, telefonoDAO);
        ctrlTelefono = new ControladorTelefono(telefonoDAO);
        //instanciar vistas
        ventanaIniciar = new VentanaIniciarSesion();
        ventanaRegistrar = new VentanaRegistrarUsuario();
    }

    public JMenu getMenuAgenda() {
        return menuAgenda;
    }

    public JMenuItem getMenuItemCerrar() {
        return menuItemCerrar;
    }

    public JMenuItem getMenuItemIniciarSesion() {
        return menuItemIniciarSesion;
    }

    public JMenuItem getMenuItemListarUs() {
        return menuItemListarUs;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuItemIniciar = new javax.swing.JMenu();
        menuItemIniciarSesion = new javax.swing.JMenuItem();
        menuItemRegistar = new javax.swing.JMenuItem();
        menuItemListarUs = new javax.swing.JMenuItem();
        menuItemCerrar = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        menuItemAgregar = new javax.swing.JMenuItem();
        menuItemBuscar = new javax.swing.JMenuItem();
        menuItemActualizar = new javax.swing.JMenuItem();
        menuItemEliminar = new javax.swing.JMenuItem();
        menuItemListar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuItemIniciar.setMnemonic('f');
        menuItemIniciar.setText("Menu");

        menuItemIniciarSesion.setMnemonic('o');
        menuItemIniciarSesion.setText("Iniciar Sesion");
        menuItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIniciarSesionActionPerformed(evt);
            }
        });
        menuItemIniciar.add(menuItemIniciarSesion);

        menuItemRegistar.setMnemonic('s');
        menuItemRegistar.setText("Registrar");
        menuItemRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistarActionPerformed(evt);
            }
        });
        menuItemIniciar.add(menuItemRegistar);

        menuItemListarUs.setMnemonic('a');
        menuItemListarUs.setText("Listar telefonos del usuario");
        menuItemIniciar.add(menuItemListarUs);

        menuItemCerrar.setText("Cerrar Sesion");
        menuItemIniciar.add(menuItemCerrar);

        menuItemSalir.setMnemonic('x');
        menuItemSalir.setText("Exit");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuItemIniciar.add(menuItemSalir);

        menuBar.add(menuItemIniciar);

        menuAgenda.setMnemonic('e');
        menuAgenda.setText("Agenda");

        menuItemAgregar.setMnemonic('t');
        menuItemAgregar.setText("Agregar");
        menuAgenda.add(menuItemAgregar);

        menuItemBuscar.setMnemonic('y');
        menuItemBuscar.setText("Buscar");
        menuAgenda.add(menuItemBuscar);

        menuItemActualizar.setMnemonic('p');
        menuItemActualizar.setText("Actualizar");
        menuAgenda.add(menuItemActualizar);

        menuItemEliminar.setMnemonic('d');
        menuItemEliminar.setText("Eliminar");
        menuAgenda.add(menuItemEliminar);

        menuItemListar.setText("Listar");
        menuAgenda.add(menuItemListar);

        menuBar.add(menuAgenda);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIniciarSesionActionPerformed
        desktopPane.add(ventanaIniciar);
        ventanaIniciar.setVisible(true);
    }//GEN-LAST:event_menuItemIniciarSesionActionPerformed

    private void menuItemRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistarActionPerformed
        desktopPane.add(ventanaRegistrar);
        ventanaRegistrar.setVisible(true);
    }//GEN-LAST:event_menuItemRegistarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemActualizar;
    private javax.swing.JMenuItem menuItemAgregar;
    private javax.swing.JMenuItem menuItemBuscar;
    private javax.swing.JMenuItem menuItemCerrar;
    private javax.swing.JMenuItem menuItemEliminar;
    private javax.swing.JMenu menuItemIniciar;
    private javax.swing.JMenuItem menuItemIniciarSesion;
    private javax.swing.JMenuItem menuItemListar;
    private javax.swing.JMenuItem menuItemListarUs;
    private javax.swing.JMenuItem menuItemRegistar;
    private javax.swing.JMenuItem menuItemSalir;
    // End of variables declaration//GEN-END:variables

}
