/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.TelefonoDAO;
import ec.edu.ups.dao.UsuarioDAO;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author braya
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private VentanaIniciarSesion ventanaIniciar;
    private VentanaRegistrarUsuario ventanaRegistrar;
    private AgregarTelefono agregarTelefono;
    private UsuarioDAO usuarioDAO;
    private TelefonoDAO telefonoDAO;
    private ControladorUsuario ctrlUsuario;
    private ControladorTelefono ctrlTelefono;
    
    private Locale localizacion;
    private ResourceBundle mensaje;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        menuItemCerrar.setVisible(false);
        menuGestionar.setVisible(false);
        //instanciar DAO's
        usuarioDAO = new UsuarioDAO();
        telefonoDAO = new TelefonoDAO();
        //instanciar Controladore
        ctrlUsuario = new ControladorUsuario(usuarioDAO, telefonoDAO);
        ctrlTelefono = new ControladorTelefono(telefonoDAO);
        //instanciar vistas
        ventanaIniciar = new VentanaIniciarSesion(ctrlUsuario,this);
        ventanaRegistrar = new VentanaRegistrarUsuario(ctrlUsuario);
        agregarTelefono = new AgregarTelefono(ctrlUsuario);
        //localizacion
        localizacion = Locale.getDefault();
        System.out.println("Pais " + localizacion.getCountry());
        //System.out.println("Idiaoma " + Localizacion.getLanguage());
        mensaje = ResourceBundle.getBundle(ec.edu.ups., localizacion);
        cambiarIdioma();
    }
    
    public void cambiarIdioma(){
//        menuMenu.setText(mensaje.getString("menuMenu"));
//            menuItemIniciarSesion.setText(mensaje.getString("menuItemIniciarSesion"));
//            menuItemRegistar.setText(mensaje.getString("menuItemRegistrar"));
//            menuItemListarUs.setText(mensaje.getString("menuItemListarUs"));
//            menuItemCerrar.setText(mensaje.getString("menuItemCerrar"));
//            menuItemSalir.setText(mensaje.getString("meniItemSalir"));
//        menuGestionar.setText(mensaje.getString("menuGestionar"));
//            menuItemtTelefono.setText(mensaje.getString("menuItemTelefono"));
//            menuItemUsuario.setText(mensaje.getString("menuItemUsuario"));
//        menuIdioma.setText(mensaje.getString("menuIdioma"));
//            menuItemEspañol.setText(mensaje.getString("menuItemEspañol"));
//            menuItemIngles.setText(mensaje.getString("menuItemIngles"));
    }
    
    public JMenu getMenuAgenda() {
        return menuGestionar;
    }

    public JMenuItem getMenuItemCerrar() {
        return menuItemCerrar;
    }

    public JMenuItem getMenuItemIniciarSesion() {
        return menuItemIniciarSesion;
    }

    public JMenuItem getMenuItemListarUs() {
        return menuItemListarUs;
    }

    public JMenuItem getMenuItemRegistar() {
        return menuItemRegistar;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menuItemIniciarSesion = new javax.swing.JMenuItem();
        menuItemRegistar = new javax.swing.JMenuItem();
        menuItemListarUs = new javax.swing.JMenuItem();
        menuItemCerrar = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuGestionar = new javax.swing.JMenu();
        menuItemtTelefono = new javax.swing.JMenuItem();
        menuItemUsuario = new javax.swing.JMenuItem();
        menuIdioma = new javax.swing.JMenu();
        menuItemEspañol = new javax.swing.JMenuItem();
        menuItemIngles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        menuMenu.setMnemonic('f');
        menuMenu.setText("Menu");

        menuItemIniciarSesion.setMnemonic('o');
        menuItemIniciarSesion.setText("Iniciar Sesion");
        menuItemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIniciarSesionActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemIniciarSesion);

        menuItemRegistar.setMnemonic('s');
        menuItemRegistar.setText("Registrar");
        menuItemRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegistarActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemRegistar);

        menuItemListarUs.setMnemonic('a');
        menuItemListarUs.setText("Listar telefonos del usuario");
        menuMenu.add(menuItemListarUs);

        menuItemCerrar.setText("Cerrar Sesion");
        menuMenu.add(menuItemCerrar);

        menuItemSalir.setMnemonic('x');
        menuItemSalir.setText("Exit");
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemSalir);

        menuBar.add(menuMenu);

        menuGestionar.setMnemonic('e');
        menuGestionar.setText("Gestionar Agenda");

        menuItemtTelefono.setMnemonic('t');
        menuItemtTelefono.setText("Tefonos");
        menuItemtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemtTelefonoActionPerformed(evt);
            }
        });
        menuGestionar.add(menuItemtTelefono);

        menuItemUsuario.setText("Usuario");
        menuGestionar.add(menuItemUsuario);

        menuBar.add(menuGestionar);

        menuIdioma.setText("Idioma");

        menuItemEspañol.setText("Español");
        menuItemEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspañolActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemEspañol);

        menuItemIngles.setText("Ingles");
        menuItemIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInglesActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemIngles);

        menuBar.add(menuIdioma);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemSalirActionPerformed

    private void menuItemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIniciarSesionActionPerformed
        desktopPane.add(ventanaIniciar);
        ventanaIniciar.setVisible(true);
    }//GEN-LAST:event_menuItemIniciarSesionActionPerformed

    private void menuItemRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegistarActionPerformed
        desktopPane.add(ventanaRegistrar);
        ventanaRegistrar.setVisible(true);
    }//GEN-LAST:event_menuItemRegistarActionPerformed

    private void menuItemtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemtTelefonoActionPerformed
        desktopPane.add(agregarTelefono);
        agregarTelefono.setVisible(true);
    }//GEN-LAST:event_menuItemtTelefonoActionPerformed

    private void menuItemEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspañolActionPerformed
//        Localizacion = new Locale("es", "EC");
//        mensajes = ResourceBundle.getBundle("ec.edu.ups.idioma.mensaje", Localizacion);
//        cambiarIdioma();
    }//GEN-LAST:event_menuItemEspañolActionPerformed

    private void menuItemInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInglesActionPerformed
//        Localizacion = new Locale("en", "UK");
//        mensajes = ResourceBundle.getBundle("ec.edu.ups.idioma.mensaje", Localizacion);
//        cambiarIdioma();
    }//GEN-LAST:event_menuItemInglesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGestionar;
    private javax.swing.JMenu menuIdioma;
    private javax.swing.JMenuItem menuItemCerrar;
    private javax.swing.JMenuItem menuItemEspañol;
    private javax.swing.JMenuItem menuItemIngles;
    private javax.swing.JMenuItem menuItemIniciarSesion;
    private javax.swing.JMenuItem menuItemListarUs;
    private javax.swing.JMenuItem menuItemRegistar;
    private javax.swing.JMenuItem menuItemSalir;
    private javax.swing.JMenuItem menuItemUsuario;
    private javax.swing.JMenuItem menuItemtTelefono;
    private javax.swing.JMenu menuMenu;
    // End of variables declaration//GEN-END:variables

}
